server:
  port: 8082

spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/nowcoder?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
  mail:
      host: smtp.qq.com #发送邮件服务器
      username: 2457476273@qq.com #QQ邮箱
      password: boorsnbuvyuwdhjb #客户端授权码
      protocol: smtps #发送邮件协议
      properties.mail.smtp.auth: true
      properties.mail.smtp.port: 465 #端口号465或587
      properties.mail.display.sendmail: Javen #可以任意
      properties.mail.display.sendname: Spring Boot Guide Email #可以任意
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8
      from: 2457476273@qq.com #与上面的username保持一致


mybatis:
  type-aliases-package: com.example.nowcoder.entiy
  mapper-locations: classpath:mapper/*.xml






